feeds:
  - https://uisneac.com/rss.xml
  - https://thedorianinvasion.substack.com/feed
  - https://amphora.substack.com/feed
  - https://www.arthwys.com/feed
  - https://bronzeagepervert.substack.com/feed
  - http://www.stoneageherbalist.com/feed
  - https://lanceslegion.substack.com/feed
  - https://ormulus.substack.com/feed
  - https://cartographer.substack.com/feed
  - https://spergler.substack.com/feed
  - https://ghostofdemaistre.substack.com/feed
  - https://chadcrowley.substack.com/feed
  - http://www.theconundrumcluster.com/feed
  - https://classicagevitalist.substack.com/feed
  - https://hyperpoiesis.substack.com/feed
  - https://theamericansun.substack.com/feed
  - https://www.theburkean.ie/feed
  - https://mansworldmag.online/feed/
  - https://putonthemask.substack.com/feed
  - https://montanaclassicalcollege.substack.com/feed
  - https://scythianbro.substack.com/feed
