# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Uisneaċ
subtitle: 'Celtic and Indo-European Research'
description: 'From ancient times until the fall of the Gaelic Order, a sacred fire at Uisneaċ was lit on Beltaine each year to initiate the Mórdáil Uisneaċ, the Great Assembly. As such Uisneaċ became spiritually the Umbilicas Hibernicae, the Navel of Ireland. It was a ceremonial gathering place for kings, possibly where the High King would symbolically marry the goddess Ériu in the banais ríghe ritual, or Marriage of the King. A fire was kept there perpetually into the Christian Age, kept alight by woman-druids in a similar fashion to Rome’s sacred flame tended by Vestal Virgins.'
keywords:
author: ogmios
language: en
timezone: ''
logo: /images/Gold-Celtic-Design.png

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://uisneac.com
permalink: :title/
permalink_defaults:
pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: draft
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true # Create new asset folder for each post
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
  - '.well-known/**'
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
plugins: hexo-tag-video
theme: cactus

# RSS by GoF
## This is the generator called fetch-feed.js, which embeds an RSS feed onto a webpage.
## List here all the RSS feeds you want displayed on the /public/feed/index.html page
external_feeds:
##  - https://uisneac.com/rss.xml
  - https://thedorianinvasion.substack.com/feed
  - https://amphora.substack.com/feed
  - https://www.arthwys.com/feed
  - https://bronzeagepervert.substack.com/feed
##  - http://www.stoneageherbalist.com/feed This substack is private now.
  - https://lanceslegion.substack.com/feed
  - https://ormulus.substack.com/feed
  - https://cartographer.substack.com/feed
  - https://spergler.substack.com/feed
  - https://ghostofdemaistre.substack.com/feed
  - https://classicagevitalist.substack.com/feed
  - https://mansworldmag.online/feed/
  - https://putonthemask.substack.com/feed
  - https://montanaclassicalcollege.substack.com/feed
  - https://scythianbro.substack.com/feed
  - https://ploughmansfolly.substack.com/feed
  - https://anbarrbuadh.substack.com/feed
  - https://polytrop0s.substack.com/feed
  - https://thuletide.wordpress.com/feed/
  - https://borealbaron.substack.com/feed/
  - https://milbel.substack.com/feed/

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: 
    github:
      url: https://github.com/uisneach/uisneach.github.io
      branch: gh-pages

emailSubmit: true

# Settings for the markdown renderer hexo-renderer-markdown-it
markdown:
  preset: 'default'
  render:
    html: true
    xhtmlOut: false
    langPrefix: 'language-'
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'
  enable_rules:
  disable_rules:
  plugins:
  anchors:
    level: 1 # This attached IDs to the headers, allowing for a TOC to form properly.
    collisionSuffix: ''
    permalink: false
    permalinkClass: 'header-anchor'
    permalinkSide: 'left'
    permalinkSymbol: '¶'
    case: 0
    separator: '-'
  images:
    lazyload: false
    prepend_root: false
    post_asset: false
  inline: false  # https://markdown-it.github.io/markdown-it/#MarkdownIt.renderInline