name: Hexo Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Trigger the workflow on pushes to the 'master' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for accurate git info

      - name: Build and Deploy
        uses: theme-keep/hexo-deploy-github-pages-action@master
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          PUBLISH_REPOSITORY: ${{ github.repository }}
          BRANCH: gh-pages  # Target branch for deployment
          PUBLISH_DIR: ./public  # Directory to deploy
