name: Hexo Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Trigger the workflow on pushes to the 'master' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write        # keep it so you can read/write code
      pages: write           # allow Pages API publishing
      id-token: write        # needed for OIDC context in Pages deploy

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build and Deploy
        uses: theme-keep/hexo-deploy-github-pages-action@master
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN_GENERAL }}
          PUBLISH_REPOSITORY: ${{ github.repository }}
          BRANCH: gh-pages
          PUBLISH_DIR: ./public

      # Add .nojekyll file and push it manually
      - name: Ensure .nojekyll in gh‑pages branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout gh-pages
          git pull --rebase origin gh-pages
          touch .nojekyll
          git add .nojekyll
          git commit -m "Add .nojekyll" || echo "No changes"
          git push origin gh-pages