# .github/workflows/fetch-feeds.yml
name: Fetch RSS Feeds

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 * * * *'  # Runs at the top of every hour (UTC)
  workflow_dispatch:


jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout default branch
        uses: actions/checkout@v4
        with:
          path: default

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      #- name: Run feed fetcher
      #  working-directory: default
      #  run: node .github/fetch_feeds.js

      - name: Run fetch_feeds.js and export to env
        id: fetch
        run: |
          # run your script and capture its stdout
          OUTPUT=$(node .github/fetch_feeds.js)

          # write it into GITHUB_ENV so it becomes an env var
          echo "FEEDS_JSON<<EOF" >> $GITHUB_ENV
          echo "$OUTPUT"         >> $GITHUB_ENV
          echo "EOF"             >> $GITHUB_ENV

      - name: Show the env var
        run: |
          echo "Here is the JSON from fetch_feeds.js:"
          echo "$FEEDS_JSON"

      - name: Debug ENV file
        run: |
          echo "---- GITHUB_ENV contents ----"
          cat $GITHUB_ENV
          echo "-----------------------------"

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Write file to target branch
        run: |
          mkdir -p "$(dirname read/rss.json)"
          echo "${{ env.FILE_CONTENT }}" > read/rss.json

      - name: Commit & push gh-pages updates
        working-directory: gh-pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add *
          git commit -m "Update RSS feeds" || echo "No changes to commit"
          git push origin gh-pages
