# .github/workflows/fetch-feeds.yml
name: Fetch RSS Feeds

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 * * * *'  # Runs at the top of every hour (UTC)
  workflow_dispatch:


jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout default branch
        uses: actions/checkout@v4
        with:
          path: default

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Run fetch_feeds.js and export to env
        working-directory: default
        id: fetch
        run: |
          OUTPUT=$(node .github/fetch_feeds.js)
          # store into GITHUB_ENV for reuse
          echo "FEEDS_JSON<<EOF" >> $GITHUB_ENV
          echo "$OUTPUT"          >> $GITHUB_ENV
          echo "EOF"              >> $GITHUB_ENV

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      # Write the captured JSON into the target file
      - name: Write feeds JSON to gh-pages
        run: |
          mkdir -p gh-pages/read
          echo "${{ env.FEEDS_JSON }}" > gh-pages/read/rss.json

      - name: Commit & push gh-pages updates
        working-directory: gh-pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add *
          git commit -m "Update RSS feeds" || echo "No changes to commit"
          git push origin gh-pages
