# .github/workflows/fetch-feeds.yml
name: Fetch RSS Feeds

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 * * * *'  # Runs at the top of every hour (UTC)
  workflow_dispatch:


jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout default branch
        uses: actions/checkout@v4
        with:
          path: default

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: List contents of .github directory
          run: echo "Contents of the .github directory:"
          run: ls -la default/.github

      - name: Run feed fetcher
        working-directory: default
        run: node .github/fetch_feeds.js

      - name: Run fetch_feeds.js and export to env
        id: fetch
        run: |
          OUTPUT=$(node .github/fetch_feeds.js)
          echo "$OUTPUT"

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Commit & push gh-pages updates
        working-directory: gh-pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add *
          git commit -m "Update RSS feeds" || echo "No changes to commit"
          git push origin gh-pages
